// <auto-generated />
using System;
using AccessFlow.Infrastructure.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccessFlow.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccessFlow.Domain.Entities.BulkOperation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<int>("ErrorProcessed")
                        .HasColumnType("integer")
                        .HasColumnName("error_processed");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("SuccessfullyProcessed")
                        .HasColumnType("integer")
                        .HasColumnName("successfully_processed");

                    b.Property<int>("UsersProcessed")
                        .HasColumnType("integer")
                        .HasColumnName("users_processed");

                    b.HasKey("Id");

                    b.ToTable("bulk_operation", (string)null);
                });

            modelBuilder.Entity("AccessFlow.Domain.Entities.BulkOperationItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<long>("IdBulkOperation")
                        .HasColumnType("bigint")
                        .HasColumnName("id_bulk_operation");

                    b.Property<long>("IdClient")
                        .HasColumnType("bigint")
                        .HasColumnName("id_client");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdBulkOperation", "IdClient")
                        .IsUnique()
                        .HasDatabaseName("ux_bulk_operation_items_operation_client");

                    b.ToTable("bulk_operation_items", (string)null);
                });

            modelBuilder.Entity("AccessFlow.Domain.Entities.Client", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_clients_email");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_clients_phone_number");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("AccessFlow.Domain.Entities.Connection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("connection_string");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("IdClient")
                        .HasColumnType("bigint")
                        .HasColumnName("id_client");

                    b.Property<string>("IdExternal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_external");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SubUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sub_url");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdExternal")
                        .IsUnique()
                        .HasDatabaseName("ux_connections_id_external");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_connections_name");

                    b.HasIndex("SubUrl")
                        .IsUnique()
                        .HasDatabaseName("ux_connections_sub_url");

                    b.ToTable("connections", (string)null);
                });

            modelBuilder.Entity("AccessFlow.Domain.Entities.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<long>("IdClient")
                        .HasColumnType("bigint")
                        .HasColumnName("id_client");

                    b.Property<long>("IdConnection")
                        .HasColumnType("bigint")
                        .HasColumnName("id_connection");

                    b.Property<DateTimeOffset?>("SendAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("send_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdConnection");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("AccessFlow.Domain.Entities.BulkOperationItem", b =>
                {
                    b.HasOne("AccessFlow.Domain.Entities.BulkOperation", "BulkOperation")
                        .WithMany("BulkOperationItems")
                        .HasForeignKey("IdBulkOperation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccessFlow.Domain.Entities.Client", "Client")
                        .WithMany("BulkOperationItems")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BulkOperation");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("AccessFlow.Domain.Entities.Connection", b =>
                {
                    b.HasOne("AccessFlow.Domain.Entities.Client", "Client")
                        .WithMany("Connections")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("AccessFlow.Domain.Entities.Notification", b =>
                {
                    b.HasOne("AccessFlow.Domain.Entities.Client", "Client")
                        .WithMany("Notifications")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AccessFlow.Domain.Entities.Connection", "Connection")
                        .WithMany("Notifications")
                        .HasForeignKey("IdConnection")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("AccessFlow.Domain.Entities.BulkOperation", b =>
                {
                    b.Navigation("BulkOperationItems");
                });

            modelBuilder.Entity("AccessFlow.Domain.Entities.Client", b =>
                {
                    b.Navigation("BulkOperationItems");

                    b.Navigation("Connections");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("AccessFlow.Domain.Entities.Connection", b =>
                {
                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
